#!/bin/bash
set -e

source $(dirname $0)/version
cd $(dirname $0)/..

set -x

# patches
if [ -n "${NOPATCHES}" ]; then
    exit 0
fi
#PATCHES_DIR=$(pwd)/patches
#pushd build/kernel
#for p in $(find ${PATCHES_DIR} -name "*.patch"); do
#    echo "applying $p"
#    patch -p1 -i $p
#done
#popd
